################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ Traditional Chinese language ##################
[zh-tw]
languageName = "繁體中文"
languageCode = "zh-Hant"
contentDir = "content/zh-tw"
weight = 2
