################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ French language ##################
[fr]
languageName = "Français"
languageCode = "fr-FR"
contentDir = "content/french"
weight = 2

################ Italian language #################
[it]
languageName = "Italiano"
languageCode = "it-IT"
contentDir = "content/italian"
weight = 3

################ German language ##################
[de]
languageName = "German"
languageCode = "de-at"
contentDir = "content/german"
weight = 4

################ Traditional Chinese language ##################
[zh-tw]
languageName = "繁體中文"
languageCode = "zh-tw"
contentDir = "content/zh-tw"
weight = 5