[[footer]]
name = "À propos"
url = "about/"
weight = 2
[[footer]]
name = "Projet"
url = "project/"
weight = 3
[[footer]]
name = "Service"
url = "service/"
weight = 4
[[footer]]
name = "Tarification"
url = "pricing/"
weight = 5
[[footer]]
name = "Questions fréquentes"
url = "faq/"
weight = 6
[[footer]]
name = "Contact"
url = "contact/"
weight = 7
[[main]]
name = "首頁"
url = ""
weight = 1
[[main]]
name = "最新消息"
url = "blog/"
weight = "2"
[[main]]
name = "近期活動"
url = "activity/"
weight = "3"
[[main]]
name = "關於我們"
url = "about/"
weight = "4"
[[main]]
name = "遊戲作品"
url = "project/"
weight = "5"
