[[footer]]
name = "About"
url = "about/"
weight = 2
[[footer]]
name = "Project"
url = "project/"
weight = 3
[[footer]]
name = "Service"
url = "service/"
weight = 4
[[footer]]
name = "Pricing"
url = "pricing/"
weight = 5
[[footer]]
name = "FAQ"
url = "faq/"
weight = 6
[[footer]]
name = "Contact"
url = "contact/"
weight = 7
[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "About"
url = "about/"
weight = 2
[[main]]
name = "News"
url = "/blog"
weight = "4"
[[main]]
name = "Project"
url = "project/"
weight = 5
[[main]]
name = "Activity"
url = "activity/"
weight = 3