---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: subtitle
  label: subtitle
  description: this is meta description
- name: description
  type: text
  config:
    required: false
  label: description
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- type: file
  name: title_image
  label: title_image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
- name: platform
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: name
  - name: url
    type: text
    config:
      required: false
    label: url
  config:
    min: 
    max: 
    labelField: 
  label: platform
- name: screenshot_image_carousel
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: image
  config:
    min: 
    max: 
    labelField: 
  label: screenshot_image_carousel
pages:
- exampleSite/content/zh-tw/project/_shape-of-my-mind.md
- exampleSite/content/zh-tw/project/cyberrupt.md
- exampleSite/content/zh-tw/project/dazzling.md
- exampleSite/content/zh-tw/project/forestry-1.md
- exampleSite/content/zh-tw/project/johnwicksimulation.md
- exampleSite/content/zh-tw/project/move-up.md
- exampleSite/content/zh-tw/project/star-tracer.md
- exampleSite/content/zh-tw/project/torichk.md
- exampleSite/content/zh-tw/project/來自曼查農場的唐吉鴨達克.md
- exampleSite/content/zh-tw/project/前輩我喜歡你的鳳梨蝦球啊.md
- exampleSite/content/zh-tw/project/救救腦殘同胞.md
- exampleSite/content/zh-tw/project/派可的雜貨店.md
- exampleSite/content/zh-tw/project/血玫瑰.md
- exampleSite/content/zh-tw/project/迷羊.md
