---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: subtitle
  label: subtitle
  description: this is meta description
- name: descrption
  type: text
  config:
    required: false
  label: descrption
- type: file
  name: title_image
  label: title_image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
pages:
- exampleSite/content/zh-tw/project/_shape-of-my-mind.md
- exampleSite/content/zh-tw/project/test2.md
- exampleSite/content/zh-tw/project/測試作品.md
